<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta name="description" content="seth food delivery is a premium food delivery service with the mission to bring affordable and healthy meals to many people as possible.">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">';
echo '<link rel="stylesheet" type="text/css" href="vendors/css/normalize.css">';
echo '<link rel="stylesheet" type="text/css" href="vendors/css/grid.css">';
echo '<link rel="stylesheet" type="text/css" href="vendors/css/ionicons.min.css">';
echo '<link rel="stylesheet" type="text/css" href="resources/css/style.css">';
echo '<link rel="stylesheet" type="text/css" href="resources/css/queries.css">';
echo '<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet" type="text/css">';
echo '';
echo '<title>Seth's Food Chain</title>';
echo '';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<nav>';
echo '<div class="row">';
echo '<img class="logo" src="resources/img/logo.png" alt="Seth's Food Chain Logo">';
echo '<img class="logo-sticky" src="resources/img/logo.png" alt="Seth's Food Chain Logo">';
echo '<ul class="main-nav js--main-nav">';
echo '<li><a href="#features">Food Delivery</a></li>';
echo '<li><a href="#works">How it works</a></li>';
echo '<li><a href="#cities">Our Cities</a></li>';
echo '<li><a href="#plans">Sign Up</a></li>';
echo '</ul>';
echo '<a class="mobile-nav-icon js--nav-icon"><i class="ion-navicon-round"></i></a>';
echo '</div>';
echo '</nav>';
echo '<div class="hero-text-box">';
echo '<h1>Goodbye, Junk food. <br>Hello healthy meals</h1>';
echo '<a class="btn btn-full js--scroll-to-plans" href="#">I'm Hungry</a>';
echo '<a class="btn btn-ghost js--scroll-to-start" href="#">Show me more</a>';
echo '</div>';
echo '</header>';
echo '';
echo '<section class="section-features js--section-features" id="features">';
echo '<div class="row">';
echo '<h2>Get Food fast &mdash; not fast food</h2>';
echo '<p class="long-copy">';
echo 'Hello, we’re Seth's Food Chain, your new premium food delivery service. We know you’re always busy. No time for cooking. So let us take care of that, we’re really good at it, we promise!';
echo '</p>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col span-1-of-4 box">';
echo '<i class="ion-earth icon-big"></i>';
echo '<h3>Up to 365 days/year</h3>';
echo '<p>';
echo 'Never cook again! We really mean that. Our subscription plans include up to 365 days/year coverage. You can also choose to order more flexibly if that's your style.';
echo '</p>';
echo '</div>';
echo '<div class="col span-1-of-4 box">';
echo '<i class="ion-clock icon-big"></i>';
echo '<h3>Ready in 20 minutes</h3>';
echo '<p>';
echo 'You're only twenty minutes away from your delicious and super healthy meals delivered right to your home. We work with the best chefs in each town to ensure that you're 100% happy.';
echo '</p>';
echo '</div>';
echo '<div class="col span-1-of-4 box">';
echo '<i class="ion-ios-nutrition-outline icon-big"></i>';
echo '<h3>100% organic</h3>';
echo '<p>';
echo 'All our vegetables are fresh, organic and local. Animals are raised without added hormones or antibiotics. Good for your health, the environment, and it also tastes better!';
echo '</p>';
echo '</div>';
echo '<div class="col span-1-of-4 box">';
echo '<i class="ion-ios-telephone-outline icon-big"></i>';
echo '<h3>Order anything</h3>';
echo '<p>';
echo 'We don't limit your creativity, which means you can order whatever you feel like. You can also choose from our menu containing over 100 delicious meals. It's up to you!';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '<section class="section-meals">';
echo '<ul class="meals-showcase clearfix">';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/1.jpg" alt="Korean bibimbap with egg and vegetables">';
echo '</figure>';
echo '</li>';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/2.jpg" alt="Simple italian pizza with cherry tomatoes">';
echo '</figure>';
echo '</li>';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/3.jpg" alt="Chicken breast steak with vegetables">';
echo '</figure>';
echo '</li>';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/4.jpg" alt="Autumn pumpkin soup">';
echo '</figure>';
echo '</li>';
echo '</ul>';
echo '<ul class="meals-showcase clearfix">';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/5.jpg" alt="Paleo beef steak with vegetables">';
echo '</figure>';
echo '</li>';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/6.jpg" alt="Healthy baguette with egg and vegetables">';
echo '</figure>';
echo '</li>';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/7.jpg" alt="Burger with cheddar and bacon">';
echo '</figure>';
echo '</li>';
echo '<li>';
echo '<figure class="meal-photo">';
echo '<img src="resources/img/8.jpg" alt="Granola with cherries and strawberries">';
echo '</figure>';
echo '</li>';
echo '</ul>';
echo '</section>';
echo '';
echo '<section class="section-steps" id="works">';
echo '<div class="row">';
echo '<h2>How it works &mdash; Simple as 1, 2, 3</h2>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-2 steps-box">';
echo '<img src="resources/img/iphone.png" alt="sethfodd app on iphone" class="app-screen js--wp-2">';
echo '</div>';
echo '<div class="col span-1-of-2 steps-box">';
echo '<div class="works-step">';
echo '<div>1</div>';
echo '<p>Choose the subscription plan that best fits your needs and sign up today.</p>';
echo '</div>';
echo '<div class="works-step">';
echo '<div>2</div>';
echo '<p>Order your delicious meal using our mobile app or website. Or you can even call us!</p>';
echo '</div>';
echo '<div class="works-step">';
echo '<div>3</div>';
echo '<p>Enjoy your meal after less than 20 minutes. See you the next time!</p>';
echo '</div>';
echo '';
echo '<a href="#" class="btn-app"><img src="resources/img/app-andriod.png" alt="Andriod Btn"></a>';
echo '<a href="#" class="btn-app"><img src="resources/img/download-app.svg" alt="Apple Btn"></a>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section-cities" id="cities">';
echo '<div class="row">';
echo '<h2>We're currently in these cities</h2>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-4 box">';
echo '<img src="resources/img/NE.jpg" alt="nueva ecija">';
echo '<h3>NUEVA ECIJA</h3>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-person icon-small"></i>';
echo '1600+ Happy Eaters';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-star icon-small"></i>';
echo '35+ chefs';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-social-facebook icon-small"></i>';
echo '<a href="#">@melvin.tecson</a>';
echo '</div>';
echo '</div>';
echo '<div class="col span-1-of-4 box">';
echo '<img src="resources/img/bulacan.jpg" alt="bulacan">';
echo '<h3>BULACAN</h3>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-person icon-small"></i>';
echo '1900+ Happy Eaters';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-star icon-small"></i>';
echo '25+ chefs';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-social-facebook icon-small"></i>';
echo '<a href="#">@melvin.tecson</a>';
echo '</div>';
echo '</div>';
echo '<div class="col span-1-of-4 box">';
echo '<img src="resources/img/pampanga.jpg" alt="pampanga">';
echo '<h3>PAMPANGA</h3>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-person icon-small"></i>';
echo '2500+ Happy Eaters';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-star icon-small"></i>';
echo '55+ chefs';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-social-facebook icon-small"></i>';
echo '<a href="#">@melvin.tecson</a>';
echo '</div>';
echo '</div>';
echo '<div class="col span-1-of-4 box">';
echo '<img src="resources/img/tarlac.jpg" alt="tarlac">';
echo '<h3>TARLAC</h3>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-person icon-small"></i>';
echo '1200+ Happy Eaters';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-ios-star icon-small"></i>';
echo '25+ chefs';
echo '</div>';
echo '<div class="city-feature">';
echo '<i class="ion-social-facebook icon-small"></i>';
echo '<a href="#">@melvin.tecson</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '<section class="section-testimonials">';
echo '<div class="row">';
echo '<h2>Our customers can't live without us</h2>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<blockquote>';
echo 'PUTA ANG SARAP NG MGA FOODS DITO!!';
echo '<cite><img src="resources/img/dennis.jpg" alt="Comment">Dennis Macapagal</cite>';
echo '</blockquote>';
echo '</div>';
echo '<div class="col span-1-of-3">';
echo '<blockquote>';
echo 'ANG SARAP UMORDER DITO PARANG BOYFRIEND KO!!';
echo '<cite><img src="resources/img/lourdes.jpg" alt="Comment">Lourdes Garcia</cite>';
echo '</blockquote>';
echo '</div>';
echo '<div class="col span-1-of-3">';
echo '<blockquote>';
echo 'MAPAPA WOW KA SA BILIS NG DELIVERY AT MASARAP ANG FOODS PARANG SI AMIEL!!';
echo '<cite><img src="resources/img/cherry.jpg" alt="Comment">Cherry Lou Yuzon</cite>';
echo '</blockquote>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section-plans js--section-plans"  id="plans">';
echo '<div class="row">';
echo '<h2>Start eating healthy today</h2>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<div class="plan-box">';
echo '<div>';
echo '<h3>Premium</h3>';
echo '<p class="plan-price">₱4,200 <span>/ Month</span></p>';
echo '<p class="plan-price-meal">That's only ₱150.00 per meal</p>';
echo '</div>';
echo '<div>';
echo '<ul>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>1 Meal/Dessert every day</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Order 24/7</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Access to newest creations</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Free delivery</li>';
echo '</ul>';
echo '</div>';
echo '<div>';
echo '<a class="btn btn-full" href="#">Sign up now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col span-1-of-3">';
echo '<div class="plan-box">';
echo '<div>';
echo '<h3>Pro</h3>';
echo '<p class="plan-price">₱3,200 <span>/ Month</span></p>';
echo '<p class="plan-price-meal">That's only ₱114.00 per meal</p>';
echo '</div>';
echo '<div>';
echo '<ul>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>1 Meal/Drinks every day</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Order 24/7</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Access to newest creations</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Free delivery</li>';
echo '</ul>';
echo '</div>';
echo '<div>';
echo '<a class="btn btn-full" href="#">Sign up now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col span-1-of-3">';
echo '<div class="plan-box">';
echo '<div>';
echo '<h3>Starter</h3>';
echo '<p class="plan-price">₱250 <span>/ Meal</span></p>';
echo '<p class="plan-price-meal">&nbsp;</p>';
echo '</div>';
echo '<div>';
echo '<ul>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>1 Meal, Dessert and Drinks</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Order 24/7</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>Access to newest creations</li>';
echo '<li><i class="ion-ios-checkmark-empty icon-small"></i>10% Delivery Fee</li>';
echo '</ul>';
echo '</div>';
echo '<div>';
echo '<a class="btn btn-full" href="#">Sign up now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section-form">';
echo '<div class="row">';
echo '<h2>We're happy to hear from you</h2>';
echo '</div>';
echo '<div class="row">';
echo '<form method="post" action="mailer-new.php" class="contact-form">';
echo '<div class="row">';
echo '<?php';
echo 'if ($_GET['success'] == 1) {';
echo 'echo "<div class=\"form-messages success\">Thank You! Your message has been sent!';
echo '</div>";';
echo '}';
echo 'if ($_GET['success'] == 1) {';
echo 'echo "<div class=\"form-messages error\">Opps! Something went wrong, please try again!';
echo '</div>";';
echo '}';
echo '?>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<label for="name">Name</label>';
echo '</div>';
echo '<div class="col span-2-of-3">';
echo '<input type="text" name="name" id="name" placeholder="Enter Name" required>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<label for="email">Email</label>';
echo '</div>';
echo '<div class="col span-2-of-3">';
echo '<input type="text" name="email" id="email" placeholder="Enter Email" required>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<label for="name">Contact</label>';
echo '</div>';
echo '<div class="col span-2-of-3">';
echo '<input type="tel" name="phone" id="phone" placeholder="Enter Contact" required>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<label for="find-us">How did you find us?</label>';
echo '</div>';
echo '<div class="col span-2-of-3">';
echo '<select name="find-us" id="find-us">';
echo '<option value="friends" selected>';
echo 'Friends';
echo '</option>';
echo '<option value="search">';
echo 'Search engine';
echo '</option>';
echo '<option value="ad">';
echo 'Advertisement';
echo '</option>';
echo '<option value="other">';
echo 'Other';
echo '</option>';
echo '</select>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<label>Newsletter</label>';
echo '</div>';
echo '<div class="col span-2-of-3">';
echo '<input type="checkbox" name="news" id="news" checked>Yes, please.';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<label>Drop us a message!</label>';
echo '</div>';
echo '<div class="col span-2-of-3">';
echo '<textarea name="message" placeholder="Give us a message"></textarea>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col span-1-of-3">';
echo '<label>&nbsp;</label>';
echo '</div>';
echo '<div class="col span-2-of-3">';
echo '<input type="submit" value="Send it!">';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</section>';
echo '';
echo '<footer>';
echo '<div class="row">';
echo '<div class="col span-1-of-2">';
echo '<ul class="footer-nav">';
echo '<li><a href="#">About Us</a></li>';
echo '<li><a href="#">Blog</a></li>';
echo '<li><a href="#">Press</a></li>';
echo '<li><a href="#">iOS App</a></li>';
echo '<li><a href="#">Andriod App</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="col span-1-of-2">';
echo '<ul class="social-links">';
echo '<li><a href="#"><i class="ion-social-facebook"></i></a></li>';
echo '<li><a href="#"><i class="ion-social-twitter"></i></a></li>';
echo '<li><a href="#"><i class="ion-social-googleplus"></i></a></li>';
echo '<li><a href="#"><i class="ion-social-instagram"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<p>Copyright &copy; 2020 by SethFoodChain. All rights reserved.</p>';
echo '</div>';
echo '</footer>';
echo '';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/selectivizr/1.0.3b/selectivizr.min.js"></script>';
echo '<script src="vendors/js/jquery.waypoints.min.js"></script>';
echo '<script src="resources/js/script.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>